### ISSUE TITLE
Accounts can be renamed to the empty string.

### ISSUE THREAD

**Issue by jrick** [btcsuite/Paymetheus#31]
This is both a btcwallet and a Paymetheus bug.  btcwallet should not be allowing this (waddrmgr should error), but Paymetheus should also disable the Rename button in the dialog if the text box is empty.

**Comment by jrick** [comment]
See btcsuite/btcwallet#369 for the related bug.

**Comment by davecgh** [comment]
I noticed this as well, but didn't file an issue since I knew it was possible via RPC as well.  I agree with you though that an empty account name should be disallowed and the Rename button disabled when the text box is empty.
